'use client';

import Link from 'next/link';
import { Brain, Target, TrendingUp, Zap, ArrowRight, CheckCircle } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Questions',
    description: 'Get personalized interview questions generated by AI based on your resume and target job.',
  },
  {
    icon: Target,
    title: 'Skill Matching',
    description: 'See how your skills match against job descriptions and identify gaps to work on.',
  },
  {
    icon: TrendingUp,
    title: 'Adaptive Difficulty',
    description: 'Questions get harder or easier based on your performance in real-time.',
  },
  {
    icon: Zap,
    title: 'Instant Feedback',
    description: 'Get detailed evaluation of your answers with scores and improvement suggestions.',
  },
];

const benefits = [
  'Personalized questions based on your resume',
  'Real-time adaptive difficulty',
  'Detailed scoring and feedback',
  'Track your progress over time',
  'Practice weak areas',
  'Multiple interview types',
];

export default function Home() {
  const { user } = useAuth();

  return (
    <div className="relative">
      <div className="absolute inset-0 bg-gradient-to-br from-primary-50 via-white to-accent-50 -z-10" />

      <section className="relative overflow-hidden">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-20 pb-24">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 rounded-full bg-primary-100 px-4 py-1.5 text-sm font-medium text-primary-700 mb-6">
              <Zap className="h-4 w-4" />
              AI-Powered Interview Preparation
            </div>
            <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight">
              Ace Your Next
              <span className="bg-gradient-to-r from-primary-600 to-accent-600 bg-clip-text text-transparent"> Interview</span>
            </h1>
            <p className="mt-6 text-lg sm:text-xl text-gray-600 max-w-2xl mx-auto">
              Practice with AI-generated questions tailored to your resume and target role.
              Get instant feedback, track your progress, and land your dream job.
            </p>
            <div className="mt-10 flex items-center justify-center gap-4">
              {user ? (
                <Link href="/dashboard" className="btn-primary text-base px-8 py-3 flex items-center gap-2">
                  Go to Dashboard
                  <ArrowRight className="h-5 w-5" />
                </Link>
              ) : (
                <>
                  <Link href="/register" className="btn-primary text-base px-8 py-3 flex items-center gap-2">
                    Start Practicing
                    <ArrowRight className="h-5 w-5" />
                  </Link>
                  <Link href="/login" className="btn-secondary text-base px-8 py-3">
                    Sign In
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold">Everything you need to prepare</h2>
            <p className="mt-4 text-lg text-gray-600">Comprehensive tools to help you succeed</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature) => (
              <div key={feature.title} className="card-hover p-6 text-center">
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-gradient-to-br from-primary-500 to-accent-500">
                  <feature.icon className="h-7 w-7 text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-3xl sm:text-4xl font-bold mb-6">
                How Interview IQ works
              </h2>
              <p className="text-lg text-gray-600 mb-8">
                Our AI-powered platform analyzes your resume, matches your skills with job requirements,
                and generates personalized interview questions to help you practice effectively.
              </p>
              <div className="space-y-4">
                {benefits.map((benefit) => (
                  <div key={benefit} className="flex items-center gap-3">
                    <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />
                    <span className="text-gray-700">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="card p-8 bg-gradient-to-br from-primary-50 to-accent-50 border-primary-100">
              <div className="space-y-6">
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-lg bg-primary-500 flex items-center justify-center text-white font-bold">1</div>
                  <div>
                    <h4 className="font-semibold">Upload Resume</h4>
                    <p className="text-sm text-gray-600">Upload your resume for skill extraction</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-lg bg-primary-500 flex items-center justify-center text-white font-bold">2</div>
                  <div>
                    <h4 className="font-semibold">Set Up Interview</h4>
                    <p className="text-sm text-gray-600">Choose role, type, and difficulty</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-lg bg-primary-500 flex items-center justify-center text-white font-bold">3</div>
                  <div>
                    <h4 className="font-semibold">Practice & Improve</h4>
                    <p className="text-sm text-gray-600">Answer questions and get instant feedback</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-lg bg-primary-500 flex items-center justify-center text-white font-bold">4</div>
                  <div>
                    <h4 className="font-semibold">Track Progress</h4>
                    <p className="text-sm text-gray-600">See your scores and improvement areas</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 bg-gradient-to-br from-primary-600 to-accent-600 text-white">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            Ready to ace your interview?
          </h2>
          <p className="text-lg text-white/80 mb-8">
            Join thousands of candidates who have improved their interview skills with Interview IQ.
          </p>
          {!user && (
            <Link href="/register" className="inline-flex items-center gap-2 rounded-lg bg-white px-8 py-3 text-base font-semibold text-primary-600 shadow-lg hover:bg-gray-50 transition-all">
              Get Started for Free
              <ArrowRight className="h-5 w-5" />
            </Link>
          )}
        </div>
      </section>

      <footer className="py-8 bg-gray-900 text-gray-400 text-sm text-center">
        <p>Interview IQ &copy; {new Date().getFullYear()}. AI-powered interview preparation platform.</p>
      </footer>
    </div>
  );
}
